@startuml
title Loan Management Mobile Apps Screen Flow

start
:Start;

:Welcome Screen;

if (Registered User) then (no)
    :Click on Register;
    :Register Screen;
    :Enter Personal Information;
    :Enter Email, Phone Number and Upload Photo;
    :Click on Register Button;
    :Verification;
    :Verification Successful;
    :Login Screen;

else (yes)
    :Login Screen;
    :User enters their email and password or uses biometric authentication;

    if (biometric authentication is available) then (yes)
        :System checks if the user credentials are correct;

    else (no)
        if (using username and password is correct) then (yes)
            :System checks if the user credentials are correct;
        else (no)
            :Error: Incorrect username or password;
            stop

            :System checks if the user credentials are correct;
            if (User credentials verification) then (correct)
                :System logs the user in;
                :Dashboard;
            else (incorrect)
                :System displays an error message;
                stop

                :Dashboard;
                :View Loan Information;
                :Loan Information;
                :Current Loan Details;
                :Loan Amount Borrowed;
                :Loan Amount Remaining;
                :Apply for Loan;
                :Loan Application Form;
                :Enter Loan Amount;
                if(Loan Amount > 12.000.000) then (yes)
                    :Error: Amount Can't > 12.000.000;
                    :End;
                else (no)
                    :Select Tenor;
                    if(Tenor > 1 Year) then (yes)
                        :Error: Tenor Can't > 1 Year;
                        :End;
                    else (no)
                        :Review Information;
                        :Submit Loan Application;
                        :View Loan Status;
                        if (Loan Status is Ongoing) then (yes)
                            :Error: Loan Ongoing;
                            :End;
                        else (no)
                            :Apply for Loan;
                            if (Loan Eligibility Check) then (no)
                                :Error: Loan Eligibility Check Failed;
                            else (yes)
                                :System Review;
                                if (Loan Application Approved) then (yes)
                                    :Notify via Email and Phone;
                                    :Loan Approval;
                                    :Disburse Loan;
                                    :Loan Repayment;
                                    :End;
                                else (no)
                                    :Notify via Email and Phone;
                                    :Loan Rejection;
                                    :End;

                                    @enduml